DELIMITER //
 CREATE PROCEDURE GetSchedulers()
   BEGIN
   
   select id as schedulerStatsId,
	COBALT_SCHEDULER,
     XTIME_SCHEDULER,
     OTHER_XTIME,
     AUTO_APPOINTMENTS_SCHEDULER,
     TIME_HIGHWAY_SCHEDULER,
     VIN_SOLUTION_SCHEDULER,
     MY_VEHICLE_SITE_SCHEDULER,
     TOTAL_CUSTOMER_CONNECT_SCHEDULER,
     DEALER_CONNECTION_SCHEDULER,
     ADP_SCHEDULER,
     ADP_SCHEDULER_BACKUP,
     ADP_OLD_SCHEDULER,
     ADP_OLD_SCHEDULER_ALTERNATIVE,
     SHOPWATCH_SCHEDULER,
     ACUITY_SCHEDULER,
     CIMA_SYSTEMS,
     CIMA_SYSTEMS_SECONDARY,
     UDC_REVOLUTION,
     DEALER_SOCKET,
     DEALER_FX_SCHEDULER,
     SERVICE_BOOK_PRO_SCHEDULER,
     AD_WORKZ_SCHEDULER,
     CAR_RESEARCH_SCHEDULER,
     DRIVERSIDE_SCHEDULER,
     DEALERMINE_SCHEDULER,
     PBS_SYSTEMS_SCHEDULER,
     LEAD_RESULT_SCHEDULER,
     SCHEDULE_WEB_PRO_SCHEDULER,
     REYNOLDS_SCHEDULER
from schedulerstats;
   END 